apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: vcluster-demo-flux
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '*'
  interval: 1m
  kubeConfig:
    secretRef:
      name: vcluster-flux-kubeconfig
      key: config
  releaseName: podinfo
  targetNamespace: podinfo
  install:
    createNamespace: true
  values:
    ui:
      message: "Deployed by Flux to virtual cluster - sweet"
    ingress:
      enabled: true
      hosts:
        - host: podinfo.example.com
          paths:
            - path: /
              pathType: Prefix